port-labs/port-k8s-exporter

pkg/port/cli/entity.go
Support merge of properties of existing entity.
=> Add merge=true query param to create entity

pkg/config/config.go, pkg/handlers/controllers.go, pkg/k8s/controller.go, pkg/k8s/controller_test.go, pkg/port/models.go
=> PORT-8228 Add UpdateEntityOnlyOnDiff to mapping

main.go, pkg/config/config.go, pkg/k8s/controller.go, pkg/port/models.go
=> PORT-8394 Enable updateEntityOnlyOnDiff by default

pkg/jq/parser.go, pkg/k8s/controller_test.go, pkg/port/mapping/entity.go, pkg/port/models.go
=> PORT-8514 search relation support

pkg/handlers/controllers.go, pkg/k8s/controller.go, pkg/k8s/controller_test.go, pkg/parsers/sensitive.go, pkg/port/cli/integration.go, pkg/port/integration/integration.go, pkg/port/models.go
What - Add support for post integration kind examples
=> Port 8710 git git hub bitbucket data k 8 s source add live examples

pkg/config/config.go
What - Upgraded yaml version usage
Why - struct loading is bit different between the 2 version and causes inconsistency
=> Upgraded yaml version usage

Dockerfile
What - Bump and lock the alpine version used in our `Dockerfile`
Why - Ensure latest security patches and make sure that we control the upgrades explicitly
=> Bump and lock alpine version

Dockerfile
=> Make alpine version dependency without pebble

pkg/port/cli/entity.go, pkg/port/entity/entity.go
Update checking entity ownership to check `stateKey` with parentheses.
=> Fix bug with entities ownership

go.mod
What - increased golang version
Why - some vulnerabilities got fixed
How - Increase go version  in go.mod
=> Increased go version

Dockerfile
=> Bump alpine image to 3.21.3

.github/workflows/docker-images-security-scan.yml
=> Add Docker images scan workflow

.github/workflows/docker-images-security-scan.yml
=> Scan docker images

.github/workflows/go.yml
=> Fix comment on PR step

pkg/handlers/controllers.go
What - make the sync be sequential in case of CreateMissingRelatedEntities flag not raised
Why - clients are facing a lot of failures on their logs when the flag is not raised because of "not found" entities issue cause by the parallel native of the exporter
How - choose the behavior according to the flag enablement
=> [PORT-12903] sequential sync in case of CreateMissingRelatedEntities flag not raised

.github/workflows/release.yml, .goreleaser.yaml, pkg/event_handler/consumer/consumer_test.go
=> replace musl for cross-platform compiling

.github/workflows/release.yml, .goreleaser.yaml
=> fix goreleaser config

.goreleaser.yaml
=> fix path to compiler

.github/workflows/go.yml, .github/workflows/release.yml, go.mod, pkg/config/config_test.go, pkg/goutils/env_test.go, pkg/goutils/map_test.go, pkg/goutils/slices_test.go
What - Upgrade Go version
Why - Vulnerability
How -
=> update go version

pkg/handlers/controllers_test.go, pkg/port/cli/entity.go, pkg/port/models.go
What - use a new efficient route in portapi for datasource rules query
Why - efficiency
How - new route implementation
=> added support for new datasource route

.goreleaser.yaml, main.go, pkg/defaults/defaults_test.go, pkg/defaults/init.go, pkg/event_handler/polling/polling_test.go, pkg/handlers/controllers_test.go, pkg/port/integration/integration.go, version.go
What - Inject version to the exporter on the build phase
Why - Ablity to track exporter version
How -
=> inject version on build

pkg/defaults/init.go
What - Patch the integration version on port
Why - Upgrading users
How -
=> patch integration version on port

.gitignore
What - Ignore generated binary file
=> Ignore generated binary file

pkg/handlers/controllers.go, pkg/k8s/controller.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
Populated missing label set of failed extraction phase in the object count metric, and change check in tests to verify population correctly
=> Populate metric and fix check in all tests
