pkg/k8s/resource.go

Allows more flexible definition of the kind in the mapping configuration (accept `singular` and `kind` resource names in addition to `plural`)

Use discovery mapper first resource result when available

---

pkg/config/config.go
pkg/handlers/controllers.go
pkg/k8s/controller.go
pkg/k8s/controller_test.go

- Map only identifier and blueprint in get entities for delete stale entities to avoid failures when there is an issue with other mappings (for properties and relations for example).
- Aggregate resources by kind for controller, to avoid `concurrent map read and map write` in K8s SDK when interacting with the same object concurrently.

Map only identifier and blueprint in get entities for delete stale entities, and aggregate resources by kind

---

.github/workflows/release.yml
Dockerfile

The docker file is currently failing for 
```
Error response from daemon: unable to find user nonroot: no matching entries in passwd file
```
because we changed base image and now nonroot user does not exists
reverting to the old image

revert to the old image

---

main.go

The current version (chart - 0.2.8; app - 0.2.8) of the k8s exporter fails to load with the -v parameter because the `klog.initFlags` function is called in the main function instead of being called from the init function
Fixed the call for this function

initing the klog.InitFlags from the init() function

---

pkg/k8s/controller.go
pkg/k8s/controller_test.go

https://getport.atlassian.net/browse/PORT-6027

Port 6027 delete entities by owner

---

pkg/config/config.go
pkg/config/models.go
pkg/config/utils.go
pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/defaults/init.go
pkg/port/models.go

What - Customers want to control the exporter config from their config map and not from port
Why - IAC
How - Added the OverwriteConfigurationOnRestart flag  to allow the exporter to apply the config to port on each boot

added OverwriteConfigurationOnRestart configuration

---

pkg/port/models.go

What - The integration default mapping is ignoring the value for create missing related entities
Why - The parsing key is for json and not yml
How - add parsing for yaml

fixed model to use the yaml parsing

---

pkg/port/models.go

What - Entity `title` had overridden with an empty string
Why - 
How - 

PORT-7636: empty entity title bug fix

---

pkg/jq/parser.go
pkg/k8s/controller.go
pkg/k8s/controller_test.go
pkg/port/models.go

What - Add items to parse functionallity to the mappings
Why - To ingest inner entities from base resource
The current mapping:
```yaml
port:
itemsToParse: .spec.template.spec.containers
entity:
mappings:
- identifier: .item.name + "-Container"
title: .item.name
blueprint: '"container"'
icon: '"Deployment"'
properties:
image: .item.image
relations:
deployment: .metadata.name + "-Deployment-" + .metadata.namespace
```
Will ingest the containers inside a Kubernetes deployment.
Example deployment yaml with two containers:
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
annotations:
deployment.kubernetes.io/revision: "2"
kubectl.kubernetes.io/last-applied-configuration: | …
```

Add items to parse functionallity to the mappings

---

main.go
pkg/crd/crd_test.go
pkg/defaults/defaults_test.go
pkg/event_handler/event_listener_factory.go
pkg/event_handler/polling/polling_test.go
pkg/goutils/map.go
pkg/handlers/controllers.go
pkg/jq/parser.go
pkg/k8s/controller.go
pkg/k8s/controller_test.go
pkg/port/cli/client.go

What - There was a fatal concurrent map write/read in a cahce of the informer racing with the JQ parser that uses the same object, and also while taking a look at this issue using the `go run --race` flag I found another race condition that is fixed via this PR.
Why - Bug
How - 
* Port client - Added a port client per controller rather having one globall
* Concurrent map write in entities - Deep copying the structures, less perfroment but as we don't have access to the actual object this solution will be good for now.
Adding a before + after screenshots using the `--race` flag

fix fatal both in client and in unstructured

---

.github/workflows/release.yml
go.mod

What - Bump golang version to 1.22.7
Why - Resolve vulnerabilities 
```
docker scout cves ghcr.io/port-labs/port-k8s-exporter:0.4.1
i New version 1.13.0 available (installed version is 1.2.0) at https://github.com/docker/scout-cli
✓ SBOM of image already cached, 66 packages indexed
✗ Detected 2 vulnerable packages with a total of 8 vulnerabilities
│               Analyzed Image
────────────────────┼──────────────────────────────────────────────
Target            │  ghcr.io/port-labs/port-k8s-exporter:0.4.1
digest          │  53d1a8e938bf
platform        │ linux/arm64
vulnerabilities │    1C     4H     2M     0L     1?
size            │ 30 MB
packages        │ 66
1C     4H     1M     0L     1?  stdlib 1.22.3
pkg:golang/stdlib@1.22.3
✗ CRITICAL CVE-2024-24790 …
```

bump to go 1.22.7

---

.github/workflows/go.yml
Dockerfile
Dockerfile.x86_64
pkg/crd/crd_test.go
pkg/defaults/defaults_test.go
pkg/event_handler/polling/polling_test.go
pkg/handlers/controllers_test.go
pkg/k8s/controller_test.go
pkg/port/blueprint/blueprint.go
pkg/port/cli/blueprint.go
pkg/port/models.go
test_utils/cleanup.go
test_utils/immutable.go

Updates #84
Update dockerfiles to solve CVE-2024-9143

upgrade libssl3 libcrypto3 to solve CVE-2024-9143

---

pkg/defaults/init.go

What - Added missing crdsToDiscover and overwriteCrdsActions config options to initIntegration config mapping
Why - usage of those options wasn't possible through configmap

Added missing crdsToDiscover and overwriteCrdsActions config options to initIntegration config mapping

---

pkg/defaults/defaults.go
pkg/defaults/defaults_test.go
pkg/defaults/init.go

Align logic of default resource creation with ocean, AKA if any of the blueprints already exist, skip the creation of the rest without failing

Enable multiple installations by not failing if all existing default resources exists

---

pkg/config/config.go
pkg/config/models.go
pkg/config/utils.go
pkg/defaults/defaults_test.go
pkg/defaults/init.go
pkg/event_handler/polling/polling_test.go
pkg/port/cli/integration.go
pkg/port/cli/org_details.go
pkg/port/integration/integration.go
pkg/port/models.go
pkg/port/org_details/org_details.go

What - Added support to create resources on port by default
Why -  Support onboarding experience
How - Decide which logic to execute by port FF

Port 12682 support new provisioning on k8s-exporter

---

pkg/jq/parser_test.go
pkg/k8s/controller_test.go
pkg/port/entity/entity.go
pkg/port/models.go

What -Implement support for team search in the mapping
Why - With the new ownership model, team metadata property can be configured as a search query
How - Update the relevant code and add tests.

add support for team search

---

pkg/port/cli/client.go
pkg/port/cli/client_test.go

What:
Clear any previously-set authentication token before the `POST /v1/auth/access_token` call in `pkg/port/cli/client.go`. This guarantees that the request is sent without an Authorization header.
Why:
When a stale or invalid bearer token is included in the Authorization header, Port’s API rejects the access-token request, returning 401. That blocks the exporter (and any other client) from recovering and refreshing its credentials.
How:
1. Implemented `ClearAuthToken`
2. Added a call to `ClearAuthToken` at the start of `Authenticate`.
3. Added a unit test (`TestAuthenticate_RemovesAuthorizationHeader`) to assert that no Authorization header is present.

Prevent invalid-token failures by removing Authorization header in Authenticate

---

pkg/defaults/init.go
pkg/logger/logger.go
pkg/logger/logger_test.go
pkg/port/cli/client.go

What - Wrap the refresh token timed logic with function to fix defer behavior
Why - Possible deadlock which cause pods to stuck
How - 

refresh token timer ticking logic fix

---

pkg/logger/logger.go
pkg/logger/logger_test.go

What - replace refresh token timer with pre request hook
Why - match the new authenticator obj behavior
How -

Port 15648 fix k 8 s logger token refresh

---

pkg/k8s/controller.go
pkg/k8s/controller_test.go
pkg/port/models.go

What - Added support for the `itemsToParseName` param, to allow mapping item context to another key name upon jq parse

Add itemsToParseName support
